[build]
  command   = "npm install && chmod +x node_modules/.bin/vite && node_modules/.bin/vite build"
  publish   = "dist"
  functions = "netlify/functions"

[dev]
  command    = "npm run dev"
  targetPort = 5173
  port       = 8888

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
